# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-29 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prism', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topics',
            new_name='Topic',
        ),
    ]
